### PR TITLE
add sniper&melee for jockey_skeet and allow printing to everyone

### PR DESCRIPTION
**Pull request by vikingo12**

### CODE REVIEW

**Comment by A1mDev** [comment]
Hm? This plugin is needed for another one, if you want to make prints to the chat, use the forwards from the l4d2_skill_detect plugin

**Comment by vikingo12** [comment]
l4d2_skill_detect doesnt have jockey prints + you cant skeet jockey without this plugin so its relevant to have prints and skeets in this plugin

**Comment by fantasylidong** [comment]
Will add translation output? Because skill_detect supports translation, it's a pity that this one doesn't.

**Comment by vikingo12** [comment]
Im sure anyone can understand "skeet" and "jockey"

**Comment by A1mDev** [comment]
> 
This plugin has nothing to do with killing a jockey with a melee weapon or headshotting a jockey. Of course you can't skeet the jockey without this plugin, because in the game the damage from each pellet hit in total is less than the number of lives. You have added code that loads the server and does nothing, because of this [line](https://github.com/vikingo12/L4D2-Competitive-Rework-additions/blob/e23b839291468723053d1fb4f14dc5fdbfa1e205/addons/sourcemod/scripting/l4d2_jockey_skeet.sp#L80). Also, melee weapons have a different damage logic than this plugin, melee weapons have multiple line traces, these traces do 0 damage, and only 1 trace does damage, of course, if you hit the body or head.

**Comment by SirPlease** [comment]
Good catch @A1mDev 
I would've liked to keep this PR open, but apparently you can't re-open a PR once you've merged. 😅 

Discussion on this is on-going in the dev channel on discord, will revisit this later today (promise)

**Comment by vikingo12** [comment]
had no idea about that line but make sense
about sniper & melee, I agree that they should be in skill_detect but my coding skills allow me to make only basic stuff like this but still I wanted to include some changes

**Pull request merged**
