### PR TITLE
Fix team shuffle

### PR DESCRIPTION
**Pull request by altair-sossai**
Prevents teams from being shuffled when changing maps.

### CODE REVIEW

**Comment by theletterjwithadot** [comment]
Ideally, this could replace l4d2_spec_stays_spec.sp, which usually causes teams to be mixed up (1-2 players on the wrong team) after map changes.

**Comment by vikingo12** [comment]
are u saying that it gets fixed only now? 🤣

**Comment by SirPlease** [comment]
Is there a reason you're using sb_takecontrol rather than simply changing the player to the Survivor team?
At first I thought it was to prevent Survivor duplication, but you already check if the team is full or not, which should prevent it.

**Comment by altair-sossai** [comment]
Exactly, the objective is to ensure that a duplication of a survivor does not occur.
Recently I created a plugin to perform a `!mix` between the players on my server, the plugin moved everyone to spec and then distributed the players between the teams, even respecting the number of players per team, the survivors were duplicated or ended up dead.
The alternative I found was using `sb_takecontrol`, I haven't tested using `ChangeClientTeam(client, L4D2_TEAM_SURVIVOR)`
I'll run some tests and come back with the results here.

**Comment by altair-sossai** [comment]
When using `ChangeClientTeam(client, L4D2_TEAM_SURVIVOR)` the survivor simply dies

image

**Comment by SirPlease** [comment]
Wouldn't FakeClientCommand("jointeam 2") suffice?
I know it's nitpicky, I just never really liked changing cheat flags for a plugin to function 😅

**Comment by altair-sossai** [comment]
Your concern makes perfect sense, I adjusted the code to use `FakeClientCommand("jointeam 2")`, does it make sense now?
**Observation:** I did the test using only two players, during the next few days I will test it on my server with more players involved

**Pull request merged**
