### PR TITLE
Modifications in bequiet

### PR DESCRIPTION
**Pull request by lechuga16**
- Added support to SourceTV to show general chat and team chat.
- Support will be disabled by default, this provides compatibility with text processors like (chat-processor).

### CODE REVIEW

**Comment by lechuga16** [comment]
Added a validation to prevent spam from errors like [#515](https://github.com/SirPlease/L4D2-Competitive-Rework/issues/515)
Although I can't test it, it should work.

**Comment by A1mDev** [comment]
There is no point in checking if the client index is correct in loops.

**Comment by lechuga16** [comment]
- Basically it generates a duplicate text between bequiet and simple-chatprocessor, to solve it I prefer to add variables to control the text in bequiet.
- The capital letters I will correct it now
- l4d2util is only to add IsValidClientIndex(), left4dhooks to add the team number in variables. I have an idea about that though...

**Comment by A1mDev** [comment]
I don't understand what's the problem with fixing the plugin simple-chatprocessor? Why add it here it's a public repository and half of the users or more don't use SourceTV and don't use plugin simple-chatprocessor, this plugin has long since been removed from this repository.

**Comment by A1mDev** [comment]
You can easily fix this problem in plugin simple-chatprocessor, you need to add the code [instead ](https://github.com/santosoch/insurgency/blob/316f3b054766a513acc474752a98a5f6cedef598/scripting/simple-chatprocessor.sp#L754-L761)(use the latest version of the plugin, this link is for an example and I don't know what is the actual version now):
```
bool IsValidClient(int iClient, bool bNobots = true)
{
	if (iClient < 1 || iClient > MaxClients || !IsClientInGame(iClient)) {
		return false;
	}

	if (bNobots && IsFakeClient(iClient) && !IsClientSourceTV(iClient)) {
		return false;
	}
	
	return true;
}
```

**Comment by lechuga16** [comment]
leave aside chat-prosessor, giving bequiet more flexibility to handle the text is more versatile and useful when it is not the only plugin that performs the same type of operations, now the sourcetv theme is disabled by default because it is not widely used.

**Comment by lechuga16** [comment]
I think with these changes it would be fine.

**Pull request closed without merging**
