### PR TITLE
Simplified Chinese translation for existed plugins.

### PR DESCRIPTION
**Pull request by blueblur0730**
Detailed changes:
 - Minor edit in l4d2_stats to distinguish plural gramma and "Shot" phrases in the following assistor_string.

 TODO:
 - l4d2_skill_detect may have translation sequence problem (char[] Melee(), char[] Headshot() etc..), but so far (personally think) it dose not lower the readability for players. could push it first and observe the outputs and feedbacks.

### CODE REVIEW

**Comment by apples1949** [comment]
I suggest you talk to Sir in the discord group. Many of the suits have made their own i18n, but haven't pushed it here just yet. The relevant word order needs to be renegotiated.

**Review by apples1949 — APPROVED** [review]

**Comment by apples1949** [comment]
I guessed the result long ago.

**Comment by blueblur0730** [comment]
> I guessed the result long ago.

no i just made the pr a chaos so i decided to rebase it and make a new pr

**Comment by apples1949** [comment]
You can return this commit.

**Pull request closed without merging**
