### PR TITLE
allow stats print at the end of finale in coop

### PR DESCRIPTION
**Pull request by vikingo12**

### CODE REVIEW

**Comment by SirPlease** [comment]
Considering Left4DHooks is already included, perhaps a better check would be using `L4D_HasPlayerControlledZombies()` to check if it's a versus/scavenge mode. This way we can include mutations as well. 🤔

**Comment by vikingo12** [comment]
are you saying that prints dont work for mutations? fyi I checked 2 and all of them printed stats

**Comment by vikingo12** [comment]
it prints for anything, checked realism now and it showed stats

**Comment by SirPlease** [comment]
I've taken the time to test it, as you suggested.
While the code does technically execute, it appears to not function exactly as you intended.
Specifically, it seems to use the **versus/other** section on mutations, even when dealing with co-op mutations. This results in a shorter waiting time of only `2` seconds before the print command executes, instead of the intended `8` seconds.

The `finale_vehicle_leaving` event might not be necessary for versus matchmodes, given that the `round_end` trigger is already in place and works fine in versus.

Given the things above, I've gotten rid of the `mp_gamemode` method entirely as it was also relied upon within `round_end` and replaced them with my suggested `L4D_HasPlayerControlledZombies` method.
This should have the desired outcome you were attempting to add.

**Pull request closed without merging**
