### PR TITLE
Fixed double voting (builtinvotes.ext)

### PR DESCRIPTION
**Pull request by A1mDev**
Fixed double voting builtinvotes.ext, no plugin updates required.

### CODE REVIEW

**Comment by jensewe** [comment]
`int players[MaxClients];`
Probably invalid to do so, because `MaxClients` is a global variable.
Supposed to be initiated as `int[] players = new int[MaxClients];`

Found those at Line 228, 571, 600, 642, 667

**Comment by A1mDev** [comment]
To do this, you need to use the native - BuiltinVote_IsVoteInProgress(). This will return true if the builtinVote is in progress. In any case, some plugins will have to be fixed, but it's better than fixing every plugin using builtinvotes.

[BV] Native Game_IsVoteInProgress(). Couldn't find the vote_controller - regarding this error, I'll see why this happens, but it doesn't break anything, so you can ignore these errors for now.

**Comment by A1mDev** [comment]
@jensewe, yes i will fix it now!

**Comment by A1mDev** [comment]
[BV] Native Game_IsVoteInProgress(). Couldn't find the vote_controller.
This error occurs due to the fact that the native IsBuiltinVoteInProgress() is used when changing the map. I will try to determine the exact moment when the vote_controller will be destroyed, to improve the code. =)

**Pull request merged**
