### PR TITLE
checkpoint-rage-control

### PR DESCRIPTION
**Pull request by lechuga16**
+ added player_death hook for player managed tanks
+ an unhook was added in the round start event.

Thanks to Forgetest for the suggestions.

### CODE REVIEW

**Comment by SirPlease** [comment]
Player_death will also trigger for AI Tanks, keeping tank_killed in there is redundant.

**Comment by SirPlease** [comment]
Player_death will also trigger for AI Tanks, keeping tank_killed in there is redundant.

**Comment by lechuga16** [comment]
You are right, I will take the opportunity to change something else.

**Comment by theletterjwithadot** [comment]
There are two copies of the compiled plugin in different directories with different file sizes.

> ../plugins/**fixes**/checkpoint-rage-control.smx

and

> ../plugins/**optional**/checkpoint-rage-control.smx

**Comment by lechuga16** [comment]
true, the one in /fixes/ is the version that had the redundant code and the one in /optional/ is the one that is clean.
my mistake in putting them in their respective directory

**Pull request merged**
