### PR TITLE
Fix inconsistent SI classes of first hit

### PR DESCRIPTION
**Pull request by jensewe**
Reported by and thanks to [this guy](https://steamcommunity.com/profiles/76561198017350428/).

### CODE REVIEW

**Comment by lunatixxx** [comment]
Does that fix this issue when sometimes players have multiple hunters on first hit?

**Comment by jensewe** [comment]
> Does that fix this issue when sometimes players have multiple hunters on first hit?

Yep if the config doesn't allow

**Comment by lunatixxx** [comment]
I tried the plugin but it did the contrary, the classes were different on first hit when it was consistent before. But i am not using fix_spawn_order maybe it is why.

**Comment by jensewe** [comment]
no, nothing to do with sack order, as long as no plugin affects the first line-up.

**Pull request merged**
