### PR TITLE
 ban some unreasonable tanks in [dbd dc]

### PR DESCRIPTION
**Pull request by AidenVii**
changes on [dead before down dc]
map 3: block a stuck spot at 73% store, tank cant get out
map 4: remove the glasses of 'ride rockit', may block tank spawn
map 4: ban 36%~49% tank - after handl stair ,may very close to svv
map 4: ban 57%~63% tank - jump the 'platform'
map 4: ban 67%~75% tank - through the vent
fix some wrong words in mapinfo.txt (wont affect anything)

### CODE REVIEW

**Review by StarterX4 — COMMENTED** [review]
I guess this is by an accident, but your PR also brings **older** versions of plugins and gamedata.

**Comment by AidenVii** [comment]
> I guess this is by an accident, but your PR also brings **older** versions of plugins and gamedata.

yeah, i saw them ,sorry for that, i dont know how to stop the old data affect my changing,I'm working on the problem

**Comment by fantasylidong** [comment]
You can create a mew branch from latest sirplease repo master branch. Then make your change at your new branch. After test, make a pull request from new branch to sirplease master branch.

**Comment by AidenVii** [comment]
now i recover the extra or old changes files, keep the right parts and checked them ,really sorry for the trouble of these, i will be careful

**Pull request merged**
