### PR TITLE
Fix many plugins after l4d2 update.

### PR DESCRIPTION
**Pull request by A1mDev**
All offsets have changed in class 'CTerrorPlayer', now it is offset - 32. If there is the next update of the game, it will be easier for us to fix the plugins!

Fix of offsets after the update, now it will dynamically find new offsets if possible, the rest will be in the gamedata 'l4d2_si_ability', and updating the syntax. It was hard to find it and fix it, and these are not all plugins requiring updating. Thanks @Rena for giving me a hint.

1. si_fire_immunity -> called every time 'ExtinguishEntity(client)', if attacker == 0, i.e any object, not a player. Due to the fact that in the event the string 'weapon' is always empty. It also created a bunch of unnecessary timers with checks. For the reason that the event 'player_hurt' is very often called, this could affect performance to some extent. Add cvars 'infected_extinguish_time' and 'tank_extinguish_time', how long will it take for an infected or tank to be extinguished.
2. l4d_jockey_ledge_hang -> Not quite correct work with game timers (CountdownTimer), it is not clear which timer we tried to update in the class 'CLeap' there are two of them (good that sourcemod did it right). Removed old code, new code works better.
3. l4d2_smoker_drag_damage_interval -> l4d2_smoker_drag_damage_interval_zone.smx, fixed incorrect work with game timer (CountdownTimer).
4. infected_flow_warp, it created variables without initialization, there was garbage from memory, and then tried to use, this could potentially break the server, the new method will work better. Besides, the old code worked badly, there was no sorting by distance. Now you can use the command !warpto without arguments, and you will be thrown to the farthest survivor, or use character names !warpto nick.
5. Fixed all compilation warnings except enum struct.
6. Fixed CTerrorPlayer offsets which can be found with, the rest are in gamedata 'l4d2_si_ability.txt'.
7. Add include 'l4d2_hybrid_scoremod.inc'.
8. Updated plugins syntax and include .
9. Fix include 'l4d2_util' plugins using it were compiled with unused variables.
10. Fixed wrong variable names, in my updated plugins.
11. Performance fixes.
12. Minor fixes.
13.  l4d2_nosey_parker - Сode improvement, fixed wrong work with ArrayStack, because of this, the plugin did not work, removed double checks from include 'l4d2util'.

### CODE REVIEW

**Comment by A1mDev** [comment]
Help me test this, otherwise I will get tired =).

**Comment by A1mDev** [comment]
How do these plugins work with these old offsets, i haven't seen any errors in the logs ??

**Comment by Derpduck** [comment]
This might be useful for finding new offsets:
https://github.com/SteamDatabase/GameTracking/commit/8652d640e03ffa330a7d709fcf16f3cc32e5902c

**Comment by A1mDev** [comment]
ok, thx =)

**Comment by jensewe** [comment]
```
public Action FirstDamage(Handle hTimer, any userid)
{
	int client = GetClientOfUserId(userid);
	if (client > 0 && GetClientTeam(client) == TEAM_SURVIVOR && IsSurvivorBeingDragged(client)) {
		int iAttacker = GetEntPropEnt(client, Prop_Send, "m_tongueOwner");
		if (IsClientInGame(iAttacker) && GetClientTeam(iAttacker) == TEAM_INFECTED) {
			float fDamage = tongue_drag_first_damage.FloatValue - 1.0;
			SDKHooks_TakeDamage(client, iAttacker, iAttacker, fDamage);
		}

		SetDragDamageInterval(client, tongue_drag_damage_interval);
		return Plugin_Continue;
	}
	
	return Plugin_Continue;
}
```
There've been a question around me since I looked into the original code.
Config uses `0.23` as the value of `tongue_drag_damage_interval`, but the comment aside claims it would be a `0.33s` interval.

> confogl_addcvar tongue_drag_damage_interval 0.23 // 3 dps (same as vanilla) [l4d2_smoker_drag_damage_interval.smx]

```
@ First Damage Enabled
	SetDragDamageInterval(client, tongue_drag_first_damage_interval);
	CreateTimer(fFirst, FirstDamage, userid, TIMER_FLAG_NO_MAPCHANGE);

@ First Damage Disabled
	SetDragDamageInterval(client, tongue_drag_damage_interval);
	float fTimerUpdate = tongue_drag_damage_interval.FloatValue + 0.1;
	CreateTimer(fTimerUpdate, FixDragInterval, userid, TIMER_REPEAT | TIMER_FLAG_NO_MAPCHANGE);
```
```
public Action FixDragInterval(Handle hTimer, any userid)
{
	int client = GetClientOfUserId(userid);
	if (client > 0 && GetClientTeam(client) == TEAM_SURVIVOR && IsSurvivorBeingDragged(client)) {
		SetDragDamageInterval(client, tongue_drag_damage_interval);
		return Plugin_Continue;
	}
	return Plugin_Stop;
}
```

> Turn off first damage:

image

> Turn on first damage:

image

Dunno if it was intended, but imo it should be avoided that inconsistency lies in the usage of "one" value. I think I will leave it here, hope anyone can help confirm this and if a fix is needed.

**Comment by A1mDev** [comment]
I did not deviate too much from the original code in this, i think you noticed correctly, but it's better to look at the @SirPlease, he supplemented this code =). I noticed something else, something else needs to be tweaked to make it more correct. I think this should work differently. Since we would update the class 'CountdownTimer', we need to do this with two variables 'm_duration' and 'm_timestamp'. Since this really points to this class, we can make sure from the source code that I commented out in the plugin. Example: https://pastebin.com/mzaxvHFW, attention should be paid to function 'SetDragDamageInterval'.

**Comment by A1mDev** [comment]
```
public int sortFunc(int index1, int index2, Handle array, Handle hndl) //working???
{
	decl item1[2];

	decl item2[2];

	if (Float:item1[1] > Float:item2[1]) {
		return -1;
	} else if (Float:item1[1] < Float:item2[1]) {
		return 1;
	} else {
		return 0;
	}
}
```
I noticed this code int plugin infected_flow_warp.smx:
1. I don't see this sorting.
2. We initialize the garbage, and then compare. It seems like it might break the server.

**Comment by A1mDev** [comment]
si_fire_immunity.smx - may not work correctly.  hEvent.GetString("weapon", weapon, sizeof(weapon)); - returns an empty string, every time we call extinguish if attacker == 0

**Comment by A1mDev** [comment]
l4d2_nosey_parkey doesn't work because ArrayStack returns 0?

**Comment by SirPlease** [comment]
> ```
> public Action FirstDamage(Handle hTimer, any userid)
> {
> 	int client = GetClientOfUserId(userid);
> 	if (client > 0 && GetClientTeam(client) == TEAM_SURVIVOR && IsSurvivorBeingDragged(client)) {
> 		int iAttacker = GetEntPropEnt(client, Prop_Send, "m_tongueOwner");
> 		if (IsClientInGame(iAttacker) && GetClientTeam(iAttacker) == TEAM_INFECTED) {
> 			float fDamage = tongue_drag_first_damage.FloatValue - 1.0;
> 			SDKHooks_TakeDamage(client, iAttacker, iAttacker, fDamage);
> 		}
> 
> 		SetDragDamageInterval(client, tongue_drag_damage_interval);
> 		return Plugin_Continue;
> 	}
> 	
> 	return Plugin_Continue;
> }
> ```
> 
> There've been a question around me since I looked into the original code.
> Config uses `0.23` as the value of `tongue_drag_damage_interval`, but the comment aside claims it would be a `0.33s` interval.
> 
> > confogl_addcvar tongue_drag_damage_interval 0.23 // 3 dps (same as vanilla) [l4d2_smoker_drag_damage_interval.smx]
> 
> ```
> @ First Damage Enabled
> 	SetDragDamageInterval(client, tongue_drag_first_damage_interval);
> 	CreateTimer(fFirst, FirstDamage, userid, TIMER_FLAG_NO_MAPCHANGE);
> 
> @ First Damage Disabled
> 	SetDragDamageInterval(client, tongue_drag_damage_interval);
> 	float fTimerUpdate = tongue_drag_damage_interval.FloatValue + 0.1;
> 	CreateTimer(fTimerUpdate, FixDragInterval, userid, TIMER_REPEAT | TIMER_FLAG_NO_MAPCHANGE);
> ```
> 
> ```
> public Action FixDragInterval(Handle hTimer, any userid)
> {
> 	int client = GetClientOfUserId(userid);
> 	if (client > 0 && GetClientTeam(client) == TEAM_SURVIVOR && IsSurvivorBeingDragged(client)) {
> 		SetDragDamageInterval(client, tongue_drag_damage_interval);
> 		return Plugin_Continue;
> 	}
> 	return Plugin_Stop;
> }
> ```
> 
> > Turn off first damage:
> 
> image
> 
> > Turn on first damage:
> 
> image
> 
> Dunno if it was intended, but imo it should be avoided that inconsistency lies in the usage of "one" value. I think I will leave it here, hope anyone can help confirm this and if a fix is needed.

It was intended, in the code we add `0.1s `to that float value, making it `0.33s`.

**Comment by jensewe** [comment]
@SirPlease Maybe I'm wrong thinking that you didn't get to the point, so I took some raw data based on Mr.A1m's modification. Feel sorry that I couldn't express myself well in a non-native language.

I would simply describe the **Zone style drag damage** and **old style (acemod) drag damage** as: _First Damage On_ and _First Damage Off_

The following are images about testing intervals between each drag damaging.

> First Damage On

image

The first 2 ticks were about first damage, and the following is the normal dragging process.
The average is a bit inaccurate because it calculates ticks beginning from the 2nd one, but it would be clear if compared to the next image.

> First Damage Off

image

There's difference around 0.1s between the two modes.

Therefore, I wondered if the **0.1s less interval** in _First Damage route_ is intended. Regardless config settings, such coding would result in the value of `tongue_drag_damage_interval` being ambiguous, and it's supposed to be avoided.

Additional tests:
image
image

**Pull request merged**
