### PR TITLE
Replaced "botpopstop" plugin + added Tank anti-rock protect on his spawn

### PR DESCRIPTION
**Pull request by BRU7U5**
- Deprecated "botpopstop" plugin and replaced by "l4d2_block_bot_pills"
> This plugin blocks bot from using pills using "Actions" extension.

- Added "l4d2_tank_spawn_antirock_protect"
> This plugin blocks a Tank player from randomly activate throw attack after his spawn.

### CODE REVIEW

**Comment by SirPlease** [comment]
Very nice suggestion of the anti-rock one, relatable mistake I've made many times. 😅 
I'll gladly accept the PR once I've ran a few tests on the block bot addition, I'm unsure about a few things with it.

**Comment by BRU7U5** [comment]
Of course, thanks! If you need help with testing or making changes to this commit - I'm willing to help.

**Comment by jensewe** [comment]
Nice works! Some minor suggestions here.

1. https://github.com/SirPlease/L4D2-Competitive-Rework/blob/17676b95e5a0b22a7906e2cec44c324d572622b5/addons/sourcemod/scripting/l4d2_block_bot_pills.sp#L41
It's probably true that no action's name is below length of 8, at least in official. But some custom actions created by plugins could probably be that case. Gotta take care of them and avoid potential errors at here.

2.. https://github.com/SirPlease/L4D2-Competitive-Rework/blob/17676b95e5a0b22a7906e2cec44c324d572622b5/addons/sourcemod/scripting/l4d2_tank_spawn_antirock_protect.sp#L29-L35
Generally there's only single tank across the whole map flow for most maps, except Dead Center 4 where there could be double tanks. This might unexpectedly block rock attempts of previous tanks whenever a new tank spawns.

**Comment by BRU7U5** [comment]
Thank you very much for the good suggestions! I will try to fix potential problems quickly as soon as I have free time

**Comment by SirPlease** [comment]
Apologies for getting back to you so late, a hunch I had was that this wouldn't prevent Survivor Bots from taking pills if they had the pills in-hand while a threat was in the area.
After testing, the bots will indeed still instantly take the pills when in-hand as they replace a player (which may be unintentional as they could've been wanting to pass pills before crashing)

I've added a simple method to prevent the bot from taking the pills instantly while also adding a full check for `SurvivorTakePills` which should resolve @jensewe 's valid concerns 😄 

I've also gone ahead and addressed the possible issue within l4d2_tank_spawn_antirock_protect.

**Pull request closed without merging**
