### PR TITLE
SG552 - Zoom out on reload

### PR DESCRIPTION
**Pull request by altair-sossai**
Remove zoom from the SG552 weapon when reloading, preventing the player's camera from getting stuck.

### CODE REVIEW

**Comment by SirPlease** [comment]
I have a few thoughts about this one, does this only happen if the weapon is currently zoomed in?
If so, does the `weapon_zoom` event trigger for this weapon? Perhaps it'd be more performance efficient to hook that event and set a bool on the player and check for that `weapon_reload` event to prevent having to check m_hActiveWeapon and using StrContains.

This would prevent the plugin from making pointless checks in configs that do not have the weapon in it.
You could also possibly instead do a quick check if the weapon is even on the map in the first place and manage a global boolean.

**Comment by altair-sossai** [comment]
Thanks for the feedback, I made some performance improvements in the plugin.
Yes, the problem only occurs when the weapon is zoomed.
Yes, the `weapon_zoom` event fires when zooming.
Can you send me an example of how I check if the weapon is present on the map or not?

**Comment by SirPlease** [comment]
I think this is fine, to be honest.
The final suggestion I'd make is to set bZoom to false on `weapon_reload` in every instance in order to resolve cases where bZoom is still set to true on the player.

**Comment by A1mDev** [comment]
Are you fixing this [issue](https://www.youtube.com/watch?v=JgFrJmZwpwk)? This problem is due to the high tick rate.

**Comment by altair-sossai** [comment]
@A1mDev, the problem was solved when reloading with the zoom, I didn't know that it also happened if the player jumped, I'll check how to solve it.

**Comment by SirPlease** [comment]
https://forums.alliedmods.net/showthread.php?p=2687318

**Pull request merged**
