### PR TITLE
Team shuffle - bug fix

### PR DESCRIPTION
**Pull request by altair-sossai**
When starting a new campaign (first map, first round), even if the score is 0 x 0, the plugin fix the teams based on the previous map.
This doesn't happen often, but when it does, players have to wait 30 seconds before being able to move between teams.
This pull request try fix that.
I'm running tests to make sure this issue is resolved once and for all, **please wait until you merge**.

### CODE REVIEW

**Comment by fantasylidong** [comment]
> players have to wait 30 seconds before being able to move between teams.

My server which installed new fix still have join team problem.

**Comment by theletterjwithadot** [comment]
It would also be good if there's a notification that prints out if someone specs or switches teams during the 30 seconds to reduce confusion as to why they are repeatedly swapped back in.

**Comment by altair-sossai** [comment]
> > players have to wait 30 seconds before being able to move between teams.
> 
> My server which installed new fix still have join team problem.
> 
> PS: In coop mode, the new fix will also cause this issue after round fail. ( my server contains coop mode which also load this fix. I will unload this fix fix in coop mode . I don't know if this is of any use to you, but I mentioned it anyway)

I just add a new commit with some fixes, I'll test it on my server in the next few days, feel free to test it on your server too.
**branch**: [https://github.com/altair-sossai/l4d2-zone-server/tree/l4d2_fix_team_shuffle_bug_fix](https://github.com/altair-sossai/l4d2-zone-server/tree/l4d2_fix_team_shuffle_bug_fix)

Regarding coop mode, I added a variable to enable/disable team correction, you can add `confogl_addcvar l4d2_fix_team_shuffle_enabled 0` in your coop mode's `shared_cvars.cfg` file

**Comment by altair-sossai** [comment]
> It would also be good if there's a notification that prints out if someone specs or switches teams during the 30 seconds to reduce confusion as to why they are repeatedly swapped back in.

I don't think it's a good idea to display a message to players, in my opinion, the best option is to disable team correction when teams are already correct.
The commit I just submitted does this, wouldn't that be a better option?

**Comment by theletterjwithadot** [comment]
> The commit I just submitted does this, wouldn't that be a better option?
Yes, that resolves the issue! 


Just a suggestion, I think it would be better to run the plugin only if the game mode is versus-based instead of having to set a cvar. 
Alot of servers (including mine) allow versus and coop modes to run instead of just versus or coop. 
Maybe replace cvar_l4d2_fix_team_shuffle_enabled with a mp_gamemode check?

**Comment by altair-sossai** [comment]
@theletterjwithadot thanks for the suggestion, I added a check using the `mp_gamemode` variable as you suggested, I think that way it solves it.

**Comment by theletterjwithadot** [comment]
Hey @altair-sossai 

Thank you for that gamemode fix. I was watching a game on Twitch and saw this happen.
https://clips.twitch.tv/TriangularInventiveTermiteDxCat-UZvIe2cTh139Ohvh

I'm not sure the version that this server is running but seems like there's a possible issue when scores are the same?
Just thought of bringing to your attention in case this hasn't been looked into.

**Comment by SirPlease** [comment]
> Thank you for that gamemode fix. I was watching a game on Twitch and saw this happen.
https://clips.twitch.tv/TriangularInventiveTermiteDxCat-UZvIe2cTh139Ohvh
>
> I'm not sure the version that this server is running but seems like there's a possible issue when scores are the same?
Just thought of bringing to your attention in case this hasn't been looked into.

Good catch, `SurvivorsAreWinning()` will always return false if the game is a tie.
I'm actually not sure what the game's default behavior is if the game ends up tied in rounds further down the line, but from map 1 to 2 it will take the team that played survivor first as the "winner" in this scenario.

I assume that same behavior goes into following rounds but this can easily be tested. (I'll go ahead and do this when I have some time available, unless of course you test it first 😄 )

**Comment by theletterjwithadot** [comment]
Would changing 
`return survivorScore > infectedScore;`
in SurvivorsAreWinning() to 
`return survivorScore >= infectedScore;`
resolve the issue?

It should produce the same results as “it will take the team that played survivor first as the “winner” in this scenario” right?

**Comment by SirPlease** [comment]
> Would changing `return survivorScore > infectedScore;` in SurvivorsAreWinning() to `return survivorScore >= infectedScore;` resolve the issue?
> 
> It should produce the same results as “it will take the team that played survivor first as the “winner” in this scenario” right?

I was typing an essay, but yes this will resolve the issue.

Also, there's no longer a need for the `IsVersus()` check, as you've already properly modified your code.
The only event in which the arrays get any data is on `L4D2_OnEndVersusModeRound_Post`, which will not fire in non-versus modes.

**Comment by theletterjwithadot** [comment]
I have pushed the latest version to my servers. Can't do a test tie score right now but I'll update when I get the chance to do. Thanks once again @altair-sossai!

**Comment by SirPlease** [comment]
After reviewing the modified code and looking through the entire plugin again, the functionality is definitely there and should be working smoothly.
However, a few things that could be improved (nitpicky 😅) are the nested loops and multiple functions for moving players to three separate teams.

Rather than looping through the array, you should be fine with using `FindValueInArray(arrayList, client) != -1`
For example:

```
public void MoveToSpectatorWhoIsNotInTheTeam(ArrayList arrayList, int team)
{
    for (int client = 1; client <= MaxClients; client++)
    {
        if (!IsClientInGame(client) || IsFakeClient(client) || GetClientTeam(client) != team || FindValueInArray(arrayList, client) != -1)
            continue;
		
        MovePlayerToTeam(client, L4D2_TEAM_SPECTATOR);
    }
}
```

```
public void MoveSpectatorsToTheCorrectTeam(ArrayList arrayList, int team)
{
    for (int client = 1; client <= MaxClients; client++)
    {
        if (!IsClientInGame(client) || IsFakeClient(client) || GetClientTeam(client) != L4D2_TEAM_SPECTATOR)
            continue;

        if (FindValueInArray(arrayList, client) != -1)
            MovePlayerToTeam(client, team);
    }
}
```

And the MovePlayerToTeam function:

```
public void MovePlayerToTeam(int client, int team)
{
    // No need to check multiple times if we're trying to move a player to a possibly full team.
    if (team != L4D2_TEAM_SPECTATOR && NumberOfPlayersInTheTeam(team) >= TeamSize())
        return;

    switch (team)
    {
        case L4D2_TEAM_SPECTATOR:
            ChangeClientTeam(client, L4D2_TEAM_SPECTATOR); 

        case L4D2_TEAM_SURVIVOR:
            FakeClientCommand(client, "jointeam 2");

        case L4D2_TEAM_INFECTED:
            ChangeClientTeam(client, L4D2_TEAM_INFECTED);
    }
}
```

**Comment by altair-sossai** [comment]
@SirPlease done!

**Comment by SirPlease** [comment]
Good stuff!
Thank you for your efforts 😄

**Pull request merged**
