### PR TITLE
Update tickrate enabler for >100 tick

### PR DESCRIPTION
**Pull request by jensewe**
Something really unnecessary while seeing who the hell picked a "128" tick server in a tournament game.

Reference: https://github.com/jensewe/Tickrate-Enabler

### CODE REVIEW

**Comment by SirPlease** [comment]
From our conversation on discord, I was under the impression that you patched the hardcoded limit of **100** for updaterate.
I'm assuming this was just a misunderstanding.
I'm not entirely sold on the idea of processing faster than clients can possibly receive. 🤔 

image

**Comment by jensewe** [comment]
This version is exactly copied from the latest artifacts that removes the hardcoded upper bound of update rate, and are tested and confirmed working.
Client update rate should follow `sv_minupdaterate` and `sv_maxupdaterate` no matter what. Any chance they are left unchaged when you're moving to higher tickrate?

And yeah I don't think every single player runs a 300fps machine while not to mention the game bugs underlying, but anyways it's just better than nothing.

**Comment by A1mDev** [comment]
The client has 100 hardcoded, I don't think you'll get more than that limit

**Comment by jensewe** [comment]
> The client has 100 hardcoded, I don't think you'll get more than that limit, besides, rates cannot be raised above 30,000 for a client

Client does have the same code but network settings would strictly follow the server's settings. Try putting `cl_cmdrate` in console while being in a server > 100 tickrate.
Though it's strange with the `rate` var, investigating.

**Comment by SirPlease** [comment]
I've confirmed with the use of Wireshark (even though I felt like this wasn't really necessary) that the client will not receive over 100 packets per second from the server, which would be the `updaterate`.
The client has no problem sending over 100, but I don't feel like this was ever the question.

For reproduction sake:
- I've only tested this on a Windows Server but I don't see why Linux would make a difference in this scenario.
- `sv_minupdaterate` and `sv_maxupdaterate` both set to **156**.

I don't mind accepting this update, but from what I understand you're claiming that you managed to allow clients to receive over 100 packets per second, which I cannot reproduce.

**Comment by jensewe** [comment]
I'm still holding the belief that it's working as long as `net_graph` shows the right value, but yeah if in reality the update rate sticks then the patch will be pointless.

netgraph

Will try validating the actual rate myself next time.

**Comment by V3nilla** [comment]
> I'm still holding the belief that it's working as long as `net_graph` shows the right value, but yeah if in reality the update rate sticks then the patch will be pointless.
> 
> netgraph
> 
> Will try validating the actual rate myself next time.

In reality old tickrate_enabler not working as intended, because its not changing client limits(30k), with your update, client can bypass rate limits, like cmdrate, before update it has 60 rate limit, after - unlimited. Tests made on Linux server with client which using Windows to play
`"cl_cmdrate" = "128" ( def. "30" ) min. 10.000000 max. 100.000000
** NOTE: The real value is 100.000 but the server has temporarily restricted it to 128.000 **`
So, it looks like your tickrate_enabler update - **Not pointless**

**Comment by A1mDev** [comment]
Where did you get the limit of 60, the client has a limWhere did you get the limit of 60, the client has a limit of 100 cmdrate, the rate limit is 30000 maxit of 100 cmdrate, the rate limit is 30000 max

**Comment by A1mDev** [comment]
I doubt that anything can be changed, because no one has yet cancelled the client code and cannot change it at the expense of the server.

**Comment by A1mDev** [comment]
I don't understand why everyone claims that it removes restrictions for the client?

**Comment by apples1949** [comment]
> How embarrassing, I only just noticed that it refused to overwrite the existing tickrate enabler with the new .dll I kept on testing with the old version 🙃
> 
> Thanks for the PR~ 👍

test on server?

**Comment by A1mDev** [comment]
Placebo effect in action :D

**Comment by SirPlease** [comment]
> I don't understand why everyone claims that it removes restrictions for the client?

Slightly confused as to what you mean, I assume you're talking about the rate limit itself?
I've just ran the same tests through wireshark that I did before regarding updaterate and I'm getting 156 updates incoming from the server to the client.

**Comment by A1mDev** [comment]
The changes affected functions `CGameClient::SetUpdateRate` and `CBaseClient::SetUpdateRate`, but they already have a limit of 100 by default, i think there will be no change for the tickrate 100.

**Comment by Localia-cn** [comment]
> > I don't understand why everyone claims that it removes restrictions for the client?
> 
> Slightly confused as to what you mean, I assume you're talking about the rate limit itself? I've just ran the same tests through wireshark that I did before regarding updaterate and I'm getting 156 updates incoming from the server to the client.

I suspect that net_graph and Wireshark may not necessarily reflect the real situation. Although the client receives UDP packets sent by the server, it may discard packets exceeding a certain threshold, depending on the client's code. A silly but effective testing approach would be to write a plugin that teleport an entity once per tick, record a video on the client side, and observe whether the entity's movement frequency matches the expected 128 ticks.

**Comment by A1mDev** [comment]
I think it would be more useful to write to the game developers and ask them to make limits like in csgo, especially since nothing will change if the servers do not increase the limits of cvars `sv_minrate, sv_maxrate, sv_mincmdrate, sv_maxcmdrate, sv_minupdaterate, sv_maxupdaterate`. Therefore, the official servers will not be affected, only community servers. Maybe then you will see a real difference.

**Comment by A1mDev** [comment]
> > > I don't understand why everyone claims that it removes restrictions for the client?
> > 
> > 
> > Slightly confused as to what you mean, I assume you're talking about the rate limit itself? I've just ran the same tests through wireshark that I did before regarding updaterate and I'm getting 156 updates incoming from the server to the client.
> 
> I suspect that net_graph and Wireshark may not necessarily reflect the real situation. Although the client receives UDP packets sent by the server, it may discard packets exceeding a certain threshold, depending on the client's code. A silly but effective testing approach would be to write a plugin that teleport an entity once per tick, record a video on the client side, and observe whether the entity's movement frequency matches the setting exceeding 100 ticks..

Yes, maybe you can get more packs, but what the game does with the extra packs is not clear, maybe you will get a negative effect from the change.

**Comment by V3nilla** [comment]
> I wrote [a simple plugin](https://github.com/Localia-cn/l4d2_tickrate_test/blob/main/l4d2_draw_tick_line.sp) for testing, which operates on the principle of drawing a TE line every tick, with each line displayed for one second. Temporary entities are more suitable for this type of testing due to their characteristic of not retransmitting lost packets, meaning that once the client discards data, it won't be displayed again.
> 
> Assuming the server is set to 150 ticks and the client's FPS is above 150, if it can stably display 150 lines, with no more than one line overlapping and brightening (due to minor timing errors), it proves that the client can receive and process data at a rate over 100 ticks.
> 
> Just say "!draw_tick" in chat. Below are the test results at 30 ticks and 60 ticks. 9f6ce632ca06d0372f875771aac73285
> 
> 0df24b2763d0ae5125cf6225e1fbeaff
> 
> I don't have a server with the new tickrate enabler installed, so can anyone test this?.

I can confirm that, tests made on server with Ubuntu 22.04. The screenshot shows 12 columns of 10 ticks each, and one has 8 ticks each
image

**Comment by fantasylidong** [comment]
Nice.👍

**Comment by Localia-cn** [comment]
Interestingly, my friend just sent me a test screenshot of his private version of the tickrate enabler, which also displayed 128 lines, but the number in the bottom right corner showed 100. So, I'm guessing that even the old version of the tickrate enabler might support 128tick, it's just that the new version resolved the issue where the client could only display 100tick. （This hypothesis has yet to be verified）
image

**Pull request merged**
