### PR TITLE
playermanagement: translation and new things

### PR DESCRIPTION
**Pull request by lechuga16**
- translation
- native to change teams to a player
- new convar sm_blockspecintank: Blocks survivors from switching to spectator to see the tank's life.
- format was applied to .sp

### CODE REVIEW

**Comment by A1mDev** [comment]
I don’t see any point in native `ChangeClientTeamEx`

**Comment by lechuga16** [comment]
It is to not depend on the servercomand:


	case TeamB:
		{
			if (L4D_GetClientTeam(iClient) == L4DTeam_Infected)
				return;

			if (GetTeamHumanCount(L4DTeam_Infected) == GetTeamMaxHumans(L4DTeam_Infected))
			{
				if (g_cvarDebug.BoolValue)
					CPrintToChatAll("%t {green}Organizing Teams{default}: %N | %s -> Spectator (Infected Full)", "Tag", iClient, L4D2_TeamName[ClientTeam]);
				ServerCommand("sm_swapto 1 #%d", GetClientUserId(iClient))
				return;
			}

			if (g_cvarDebug.BoolValue)
				CPrintToChatAll("%t {green}Organizing Teams{default}: %N | %s -> %s", "Tag", iClient, L4D2_TeamName[GetClientTeam(iClient)], L4D2_TeamName[ClientTeam]);
			ServerCommand("sm_swapto force 3 #%d", GetClientUserId(iClient));
		}

**Comment by lechuga16** [comment]
now that I think about it, it may be necessary, but at the time it seemed like a good idea 🫠

**Comment by A1mDev** [comment]
All this code can be placed in a separate include and there will be no need to use the sm_swap command

**Comment by lechuga16** [comment]
done

**Comment by SirPlease** [comment]
I'm not particularly a fan of the new feature addition being enabled by default, as it's user unfriendly.

**Comment by lechuga16** [comment]
done **x2**

**Pull request merged**
