### PR TITLE
Move fixed l4d2_si_staggers to correct directory.

### LINKED ISSUE #115: Chargers can stumble tanks in ZoneMod 1.9.9
It sounds like maybe they shouldn't be able to.

### PR DESCRIPTION
**Pull request by ProdigySim**
Fixes #115 

My PR for this in #119 accidentally put the `l4d2_si_staggers.smx` plugin in `plugins/` rather than `plugins/optional`.

This commit just does `git mv plugins/l4d2_si_staggers.smx plugins/optional/l4d2_si_staggers.smx`.

### CODE REVIEW

**Comment by ProdigySim** [comment]
@SirPlease I think we both modified this plugin in nearby commits... It might be better to just fully recompile this plugin now? Not sure if there were any changes during the merge.

**Comment by SirPlease** [comment]
The issue was more that I had it working just fine locally, so that's why I didn't notice.
I closed it in my own push, so this won't be needed.

**Comment by devilesk** [comment]
I get this error log when using the l4d2_si_staggers.smx in `plugins/optional`
```
L 10/16/2020 - 15:41:13: [SM] Exception reported: Invalid edict (-1 - -1)
L 10/16/2020 - 15:41:13: [SM] Blaming: optional/l4d2_si_staggers.smx
L 10/16/2020 - 15:41:13: [SM] Call stack trace:
L 10/16/2020 - 15:41:13: [SM]   [0] GetEdictClassname
L 10/16/2020 - 15:41:13: [SM]   [1] Line 93, D:\SourcePawn10\l4d2_si_staggers.sp::L4D2_OnStagger
L 10/16/2020 - 15:41:13: [SM]   [3] Call_Finish
L 10/16/2020 - 15:41:13: [SM]   [4] Line 6471, D:\SourcePawn10\left4dhooks.sp::OnPlayerStagger
```
I don't get the error if I switch to ProdigySim's version in `plugins`. I think the PR should be accepted.

**Comment by SirPlease** [comment]
I posted this before actually pushing to github. 🤡

**Pull request closed without merging**
