### PR TITLE
Lag compensation in `pill_passer`

### PR DESCRIPTION
**Pull request by jensewe**
Requires https://github.com/SirPlease/L4D2-Competitive-Rework/pull/684

Actually I don't even know how to prove it's really functioning, but it looks working after some tests with my bro.

### CODE REVIEW

**Comment by A1mDev** [comment]
Is the game logic really that bad for this case? The only reason you can't give pills to a player is because he might be in combat (function in game `CTerrorPlayer::IsInCombat`). You can make a patch inside the `CBaseBeltItem::SecondaryAttack` function remove the function `CTerrorPlayer::IsInCombat` from the condition.

**Comment by A1mDev** [comment]
By the way, you can remove bots when you use the hook `SDKHook_PostThink`.

**Comment by jensewe** [comment]
> Is the game logic really that bad for this case? The only reason you can't give pills to a player is because he might be in combat (function in game `CTerrorPlayer::IsInCombat`). You can make a patch inside the `CBaseBeltItem::SecondaryAttack` function remove the function `CTerrorPlayer::IsInCombat` from the condition.

I am afraid what this plugin does has nothing to do with those you mentioned. This plugin checks for players' origins and directly "transfer" their pills to aiming targets.

**Comment by A1mDev** [comment]
Game function `CBaseBeltItem::SecondaryAttack`, does the same

**Comment by vikingo12** [comment]
what is it for? doesnt R work anymore?

**Comment by jensewe** [comment]
> Game function `CBaseBeltItem::SecondaryAttack`, does the same

Not quite the same i guess, players don't need to aim directly at the target when giving pills, in other words, tolerance is introduced in there.

> what is it for? doesnt R work anymore?

An improvement for players with high latency, sometimes they can hardly pass pills to others even if aiming right straight.

**Pull request merged**
