### PR TITLE
FakeLag: Extension + Plugin integration

### PR DESCRIPTION
**Pull request by LuckyServ**
### FakeLag
FakeLag allows a game to be played on equal ping. The ideal situation is when a match is to be played on a neutral server. It could be used in any other situation, like a pug or a 1v1.

There are 2 ways to activate FakeLag.
1. An admin types the `!fakelag_start` command.
2. Players (infected team and survivor team) type the `!fakelag_votestart` command.

### Algorithm
The FakeLag algorithm finds the lowest max ping over time. There's a loop (every 4s) that checks for the max ping player, then sets the current target ping based on that players ping.

The loop also dynamically adjusts each players fakelag during the game to match the target ping.

- The target ping is only allowed to go down over time
- The target ping is reset every time a player joins the server or a team.

### Settings / Forced Values
It is possible to force the target ping with the admin command `!fakelag_force <ms>`.

There is a CVAR `sm_fakelag_max_target_ping` that defines the max automatic target ping with the default value `200`.

### CODE REVIEW

**Comment by jensewe** [comment]
cool🎉
Some suggestions for the plugin:

1. https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4ae8516d115dd3900b4234f5e3108f15a8079646/addons/sourcemod/scripting/l4d2_fakelag.sp#L30-L31 SourceMod has macros for admin flags, should be `ADMFLAG_CONFIG` in these cases.

2. https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4ae8516d115dd3900b4234f5e3108f15a8079646/addons/sourcemod/scripting/l4d2_fakelag.sp#L40 It seems nowhere else this functionality implied by the name gets defined.

3. https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4ae8516d115dd3900b4234f5e3108f15a8079646/addons/sourcemod/scripting/l4d2_fakelag.sp#L181 https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4ae8516d115dd3900b4234f5e3108f15a8079646/addons/sourcemod/scripting/l4d2_fakelag.sp#L219 https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4ae8516d115dd3900b4234f5e3108f15a8079646/addons/sourcemod/scripting/l4d2_fakelag.sp#L248 https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4ae8516d115dd3900b4234f5e3108f15a8079646/addons/sourcemod/scripting/l4d2_fakelag.sp#L307 Index at `MaxClients` is also a valid client index, while `0` stands for the server. Therefore in order to loop through clients, the init should be `int client = 1`, condition should be `client <= MaxClients`.

4. https://github.com/SirPlease/L4D2-Competitive-Rework/blob/4ae8516d115dd3900b4234f5e3108f15a8079646/addons/sourcemod/scripting/l4d2_fakelag.sp#L285-L303 I would prefer to hook on `player_team`, check the target team index there and do the reset stuff, meanwhile this whole part boils down to a single event callback.

Additionally for stock function `IsHuman`, I think it's unnecessary to validate client index according to your use cases where mostly the passed client indices are within range, only except Command Callbacks that can be invoked by server.

**Comment by SirPlease** [comment]
@jensewe You've played with the extension itself for a bit on the servers you work, right?
Have you experienced any crashes while using it?

**Comment by jensewe** [comment]
> @jensewe You've played with the extension itself for a bit on the servers you work, right? Have you experienced any crashes while using it?

According to Target there's no. Maybe refer to host of io.asia for more info.

**Comment by theletterjwithadot** [comment]
Played Carnival map 1 last night with this and no crash

These guys are very protective of their 5ms pings, so it's hard to get a game going on with the fakelag plugin.

Have got some games planned tonight, so will feedback accordingly.

**Comment by LuckyServ** [comment]
I could be wrong (maybe @ProdigySim can clarify), but it seems only the packets received by clients are delayed, not the ones sent from the server to the client.

https://github.com/ProdigySim/custom_fakelag/blob/5f1ea1b3a828a801efd578715c13619f2fdbce41/LagSystem.cpp#L15

So packets sent from the server to the client are not delayed?

For example, if an entity (ie hunter) is killed, the state update is then sent from the server to every client. If those packets aren't being delayed, then the clients with higher actual ping will receive the state update later than other clients?

**Comment by theletterjwithadot** [comment]
Fatal Freight LA pug with FakeLag plugin.
No crash, no error.

https://www.twitch.tv/videos/1290806999

**Comment by theletterjwithadot** [comment]
Got some errors to share

```
L 02/08/2022 - 12:58:50: SourceMod error session started
L 02/08/2022 - 12:58:50: Info (map "c2m1_highway") (file "/home/instance2/serverfiles/left4dead2/addons/sourcemod/logs/errors_20220208.log")
L 02/08/2022 - 12:58:50: [SM] Exception reported: Language phrase "No matching client" not found (arg 4)
L 02/08/2022 - 12:58:50: [SM] Blaming: fixes/l4d2_fakelag.smx
L 02/08/2022 - 12:58:50: [SM] Call stack trace:
L 02/08/2022 - 12:58:50: [SM]   [0] ReplyToCommand
L 02/08/2022 - 12:58:50: [SM]   [1] Line 102, C:\Users\Alexa\Documents\sourcemod-1.10.0-git6503-windows\addons\sourcemod\scripting\include\commandfilters.inc::ReplyToTargetError
L 02/08/2022 - 12:58:50: [SM]   [2] Line 193, C:\Users\Alexa\Documents\sourcemod-1.10.0-git6503-windows\addons\sourcemod\scripting\include\helpers.inc::FindTarget
L 02/08/2022 - 12:58:50: [SM]   [3] Line 141, l4d2_fakelag.sp::FakeLagCmd
L 02/08/2022 - 12:58:56: [SM] Exception reported: Language phrase "No matching client" not found (arg 4)
L 02/08/2022 - 12:58:56: [SM] Blaming: fixes/l4d2_fakelag.smx
L 02/08/2022 - 12:58:56: [SM] Call stack trace:
L 02/08/2022 - 12:58:56: [SM]   [0] ReplyToCommand
L 02/08/2022 - 12:58:56: [SM]   [1] Line 102, C:\Users\Alexa\Documents\sourcemod-1.10.0-git6503-windows\addons\sourcemod\scripting\include\commandfilters.inc::ReplyToTargetError
L 02/08/2022 - 12:58:56: [SM]   [2] Line 193, C:\Users\Alexa\Documents\sourcemod-1.10.0-git6503-windows\addons\sourcemod\scripting\include\helpers.inc::FindTarget
L 02/08/2022 - 12:58:56: [SM]   [3] Line 141, l4d2_fakelag.sp::FakeLagCmd
L 02/08/2022 - 12:59:07: [SM] Exception reported: Language phrase "No matching client" not found (arg 4)
L 02/08/2022 - 12:59:07: [SM] Blaming: fixes/l4d2_fakelag.smx
L 02/08/2022 - 12:59:07: [SM] Call stack trace:
L 02/08/2022 - 12:59:07: [SM]   [0] ReplyToCommand
L 02/08/2022 - 12:59:07: [SM]   [1] Line 102, C:\Users\Alexa\Documents\sourcemod-1.10.0-git6503-windows\addons\sourcemod\scripting\include\commandfilters.inc::ReplyToTargetError
L 02/08/2022 - 12:59:07: [SM]   [2] Line 193, C:\Users\Alexa\Documents\sourcemod-1.10.0-git6503-windows\addons\sourcemod\scripting\include\helpers.inc::FindTarget
L 02/08/2022 - 12:59:07: [SM]   [3] Line 141, l4d2_fakelag.sp::FakeLagCmd
L 02/08/2022 - 13:00:52: Error log file session closed.
```

**Comment by LuckyServ** [comment]
Unfortunately, because of the unbalanced delay issue mentionned above it looks like fakelag is not the same as true ping; we can't rely on it for fair games. Closing this MR.

Other potential way balanced ping could be done is by setting up a VPN that throttles packets both ways, but that's too involved for me right now.

**Pull request closed without merging**
