### PR TITLE
More translations and an option added to colors.inc

### PR DESCRIPTION
**Pull request by lechuga16**
Translations:
- current
- autopause (only file)
- weapon limit
- l4d2_horde_equaliser
- l4d2_tank_horde_monitor
- l4d2_tankrage
- si_class_announce
- l4d_tank_control_eq

specrates_test:
- fix

### CODE REVIEW

**Comment by SirPlease** [comment]
I'm curious as to why you'd want to increase the MAX_MESSAGE_SIZE.
From testing this will either entirely refuse to print messages when exceed the `SayText` size and at best give you a few extra characters when you're using color tags.

**Comment by lechuga16** [comment]
this solution is old, I just didn't report it before. l4d2_skill_detect prints cut message, between tests it occurred to me to increase the MAX_MESSAGE_SIZE limit and it was solved. Already allowing the limit to be modifiable would solve this type of problem.

**Comment by SirPlease** [comment]
> this solution is old, I just didn't report it before. l4d2_skill_detect prints cut message, between tests it occurred to me to increase the MAX_MESSAGE_SIZE limit and it was solved. Already allowing the limit to be modifiable would solve this type of problem.

I'm saying that once you reach the limit of SayText2 it will refuse to print it entirely, so to me it seems that modifying this will only solve some edge cases that need a few more characters (~4 characters) while it will prevent others to print at all (not even cut).
I don't consider this a solution 😅

**Comment by lechuga16** [comment]
> > this solution is old, I just didn't report it before. l4d2_skill_detect prints cut message, between tests it occurred to me to increase the MAX_MESSAGE_SIZE limit and it was solved. Already allowing the limit to be modifiable would solve this type of problem.
> 
> I'm saying that once you reach the limit of SayText2 it will refuse to print it entirely, so to me it seems that modifying this will only solve some edge cases that need a few more characters (~4 characters) while it will prevent others to print at all (not even cut). I don't consider this a solution 😅

mmmm

Screenshot_1

**Comment by lechuga16** [comment]
In any case, this commit does not deal with this error, it will be put on hold

**Pull request merged**
