### PR TITLE
Readyup - New feature and translation of the panel

### PR DESCRIPTION
**Pull request by lechuga16**
**l4d_ready_unready_limit**: If different from 0, it will indicate how many times a player can cancel the countdown, this affects only when intentionally cancelled.

**Panel**: Translation of most of the panel texts, the panel is translated according to the server language. additionally, a check has been added to the sv_maxplayers convar.

**Note**: translations to 'jp', 'chi' and 'ko' were made with AI, in case of grammatical errors.

### CODE REVIEW

**Comment by SirPlease** [comment]
I don't feel like translations should be based on the Server Language as it's not very user friendly.
I'm also not sold on AI Translations.

**Comment by lechuga16** [comment]
regarding the AI translation, it's just so that it doesn't really give an error.
regarding Server Language, I really don't think there is any other option, because when I tried to translate the panel per client, it generated errors or better said, a mix of the different client languages.

**Comment by blueblur0730** [comment]
> regarding the AI translation, it's just so that it doesn't really give an error. regarding Server Language, I really don't think there is any other option, because when I tried to translate the panel per client, it generated errors or better said, a mix of the different client languages.

Some chi translation you can have a reference here [https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/74ea52f849848d409da33a9662bc0fc90391346d](url)
As for the "changing languages" on the panel, I asumme that maybe we can send a pre-translated targeted-languege panel to the targeted-languege client? But I can imagine that would take a lot time to work on it.

**Comment by lechuga16** [comment]
Another possible solution is to create a cvar that indicates the language the panel will use. Honestly, I don't see a problem with using LANG_SERVER, as it's up to the owners to activate or not that part of the translations. Keep in mind that in translations I submit to the repository, when it comes to votes or additional panels, they also use LANG_SERVER. If this needs to be changed, for consistency, the others should be changed as well.

**Comment by lechuga16** [comment]
> > regarding the AI translation, it's just so that it doesn't really give an error. regarding Server Language, I really don't think there is any other option, because when I tried to translate the panel per client, it generated errors or better said, a mix of the different client languages.
> 
> Some chi translation you can have a reference here [https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/74ea52f849848d409da33a9662bc0fc90391346d](url) As for the "changing languages" on the panel, I asumme that maybe we can send a pre-translated targeted-languege panel to the targeted-languege client? But I can imagine that would take a lot time to work on it and yeah it's pretty hacky.

I'm working on a rework of 'Skills_detect,' and I encountered a similar issue when trying to concatenate translations. The solution was to create a function and concatenate the translations within it. Although it's resource-intensive, it was the only thing I could come up with.

```
void Print_WitchDamage(int iClient, int iDamage, int iPercentDamage, bool bHarasser, int iIsCrowned, int iShots, bool bOneShot, bool bMelee)
{
	for (int i = 1; i <= MaxClients; i++)
	{
		if (IsClientInGame(i) && (!IsFakeClient(i) || IsClientSourceTV(i)) && !CSkipList[i])
		{
			char 
				sDamage[16],
				sShots[64],
				sDetails[128];

			if (g_cvarWitchDamagePrint.BoolValue)
				Format(sDamage, sizeof(sDamage), "%d", iDamage);
			else
				Format(sDamage, sizeof(sDamage), "%d%%", iPercentDamage);

			if (bOneShot)
				Format(sShots, sizeof(sShots), "%T", "WitchDetails_OneShot", i);
			else
				Format(sShots, sizeof(sShots), "%T", "WitchDetails_Shots", i, iShots);
			
			if (g_cvarWitchDetailPrint.BoolValue)
			{
				char sTraslation[32];

				if (bHarasser)
				{
					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Harasser", i);
					StrCat(sDetails, sizeof(sDetails), sTraslation);
				}

				if (iIsCrowned)
				{
					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Crowner", i);
					StrCat(sDetails, sizeof(sDetails), sTraslation);
				}

				if (bMelee)
				{
					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Melee", i);
					StrCat(sDetails, sizeof(sDetails), sTraslation);
				}
			}
			CPrintToChat(i, "%t", "WitchDamageFormat", sDamage, sShots, iClient, sDetails);
		}

		CSkipList[i] = false;
	}
}
```

**Comment by blueblur0730** [comment]
> Another possible solution is to create a cvar that indicates the language the panel will use. Honestly, I don't see a problem with using LANG_SERVER, as it's up to the owners to activate or not that part of the translations. Keep in mind that in translations I submit to the repository, when it comes to votes or additional panels, they also use LANG_SERVER. If this needs to be changed, for consistency, the others should be changed as well.

well that is only suitable for players that use the same language.
if there's even one player who uses a different language with the others use the same on one same server, that solution won't work.

**Comment by lechuga16** [comment]
> LANG_SERVER

I think I didn't make myself clear. The convar will not be accessible to the player, only to the server. In other words, the language from the panel is imposed by the server, just like how LANG_SERVER works.

**Comment by blueblur0730** [comment]
> > > regarding the AI translation, it's just so that it doesn't really give an error. regarding Server Language, I really don't think there is any other option, because when I tried to translate the panel per client, it generated errors or better said, a mix of the different client languages.
> > 
> > 
> > Some chi translation you can have a reference here [https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/74ea52f849848d409da33a9662bc0fc90391346d](url) As for the "changing languages" on the panel, I asumme that maybe we can send a pre-translated targeted-languege panel to the targeted-languege client? But I can imagine that would take a lot time to work on it and yeah it's pretty hacky.
> 
> I'm working on a rework of 'Skills_detect,' and I encountered a similar issue when trying to concatenate translations. The solution was to create a function and concatenate the translations within it. Although it's resource-intensive, it was the only thing I could come up with.
> 
> ```
> void Print_WitchDamage(int iClient, int iDamage, int iPercentDamage, bool bHarasser, int iIsCrowned, int iShots, bool bOneShot, bool bMelee)
> {
> 	for (int i = 1; i <= MaxClients; i++)
> 	{
> 		if (IsClientInGame(i) && (!IsFakeClient(i) || IsClientSourceTV(i)) && !CSkipList[i])
> 		{
> 			char 
> 				sDamage[16],
> 				sShots[64],
> 				sDetails[128];
> 
> 			if (g_cvarWitchDamagePrint.BoolValue)
> 				Format(sDamage, sizeof(sDamage), "%d", iDamage);
> 			else
> 				Format(sDamage, sizeof(sDamage), "%d%%", iPercentDamage);
> 
> 			if (bOneShot)
> 				Format(sShots, sizeof(sShots), "%T", "WitchDetails_OneShot", i);
> 			else
> 				Format(sShots, sizeof(sShots), "%T", "WitchDetails_Shots", i, iShots);
> 			
> 			if (g_cvarWitchDetailPrint.BoolValue)
> 			{
> 				char sTraslation[32];
> 
> 				if (bHarasser)
> 				{
> 					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Harasser", i);
> 					StrCat(sDetails, sizeof(sDetails), sTraslation);
> 				}
> 
> 				if (iIsCrowned)
> 				{
> 					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Crowner", i);
> 					StrCat(sDetails, sizeof(sDetails), sTraslation);
> 				}
> 
> 				if (bMelee)
> 				{
> 					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Melee", i);
> 					StrCat(sDetails, sizeof(sDetails), sTraslation);
> 				}
> 			}
> 			CPrintToChat(i, "%t", "WitchDamageFormat", sDamage, sShots, iClient, sDetails);
> 		}
> 
> 		CSkipList[i] = false;
> 	}
> }
> ```

that seems to be a good way to be. I had thought about this problem before and I did want to print the message in language per client. Good to see you have a lot work on this

**Comment by blueblur0730** [comment]
> > > > regarding the AI translation, it's just so that it doesn't really give an error. regarding Server Language, I really don't think there is any other option, because when I tried to translate the panel per client, it generated errors or better said, a mix of the different client languages.
> > > 
> > > 
> > > Some chi translation you can have a reference here [https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/74ea52f849848d409da33a9662bc0fc90391346d](url) As for the "changing languages" on the panel, I asumme that maybe we can send a pre-translated targeted-languege panel to the targeted-languege client? But I can imagine that would take a lot time to work on it and yeah it's pretty hacky.
> > 
> > 
> > I'm working on a rework of 'Skills_detect,' and I encountered a similar issue when trying to concatenate translations. The solution was to create a function and concatenate the translations within it. Although it's resource-intensive, it was the only thing I could come up with.
> > ```
> > void Print_WitchDamage(int iClient, int iDamage, int iPercentDamage, bool bHarasser, int iIsCrowned, int iShots, bool bOneShot, bool bMelee)
> > {
> > 	for (int i = 1; i <= MaxClients; i++)
> > 	{
> > 		if (IsClientInGame(i) && (!IsFakeClient(i) || IsClientSourceTV(i)) && !CSkipList[i])
> > 		{
> > 			char 
> > 				sDamage[16],
> > 				sShots[64],
> > 				sDetails[128];
> > 
> > 			if (g_cvarWitchDamagePrint.BoolValue)
> > 				Format(sDamage, sizeof(sDamage), "%d", iDamage);
> > 			else
> > 				Format(sDamage, sizeof(sDamage), "%d%%", iPercentDamage);
> > 
> > 			if (bOneShot)
> > 				Format(sShots, sizeof(sShots), "%T", "WitchDetails_OneShot", i);
> > 			else
> > 				Format(sShots, sizeof(sShots), "%T", "WitchDetails_Shots", i, iShots);
> > 			
> > 			if (g_cvarWitchDetailPrint.BoolValue)
> > 			{
> > 				char sTraslation[32];
> > 
> > 				if (bHarasser)
> > 				{
> > 					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Harasser", i);
> > 					StrCat(sDetails, sizeof(sDetails), sTraslation);
> > 				}
> > 
> > 				if (iIsCrowned)
> > 				{
> > 					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Crowner", i);
> > 					StrCat(sDetails, sizeof(sDetails), sTraslation);
> > 				}
> > 
> > 				if (bMelee)
> > 				{
> > 					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Melee", i);
> > 					StrCat(sDetails, sizeof(sDetails), sTraslation);
> > 				}
> > 			}
> > 			CPrintToChat(i, "%t", "WitchDamageFormat", sDamage, sShots, iClient, sDetails);
> > 		}
> > 
> > 		CSkipList[i] = false;
> > 	}
> > }
> > ```
> 
> that seems to be a good way to be. I had thought about this problem before and I did want to print the message in language per client. Good to see you have a lot work on this

Guess that panels can go like this, sending them in language per client.

**Comment by lechuga16** [comment]
> > > > > regarding the AI translation, it's just so that it doesn't really give an error. regarding Server Language, I really don't think there is any other option, because when I tried to translate the panel per client, it generated errors or better said, a mix of the different client languages.
> > > > 
> > > > 
> > > > Some chi translation you can have a reference here [https://github.com/Target5150/MoYu_Server_Stupid_Plugins/commit/74ea52f849848d409da33a9662bc0fc90391346d](url) As for the "changing languages" on the panel, I asumme that maybe we can send a pre-translated targeted-languege panel to the targeted-languege client? But I can imagine that would take a lot time to work on it and yeah it's pretty hacky.
> > > 
> > > 
> > > I'm working on a rework of 'Skills_detect,' and I encountered a similar issue when trying to concatenate translations. The solution was to create a function and concatenate the translations within it. Although it's resource-intensive, it was the only thing I could come up with.
> > > ```
> > > void Print_WitchDamage(int iClient, int iDamage, int iPercentDamage, bool bHarasser, int iIsCrowned, int iShots, bool bOneShot, bool bMelee)
> > > {
> > > 	for (int i = 1; i <= MaxClients; i++)
> > > 	{
> > > 		if (IsClientInGame(i) && (!IsFakeClient(i) || IsClientSourceTV(i)) && !CSkipList[i])
> > > 		{
> > > 			char 
> > > 				sDamage[16],
> > > 				sShots[64],
> > > 				sDetails[128];
> > > 
> > > 			if (g_cvarWitchDamagePrint.BoolValue)
> > > 				Format(sDamage, sizeof(sDamage), "%d", iDamage);
> > > 			else
> > > 				Format(sDamage, sizeof(sDamage), "%d%%", iPercentDamage);
> > > 
> > > 			if (bOneShot)
> > > 				Format(sShots, sizeof(sShots), "%T", "WitchDetails_OneShot", i);
> > > 			else
> > > 				Format(sShots, sizeof(sShots), "%T", "WitchDetails_Shots", i, iShots);
> > > 			
> > > 			if (g_cvarWitchDetailPrint.BoolValue)
> > > 			{
> > > 				char sTraslation[32];
> > > 
> > > 				if (bHarasser)
> > > 				{
> > > 					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Harasser", i);
> > > 					StrCat(sDetails, sizeof(sDetails), sTraslation);
> > > 				}
> > > 
> > > 				if (iIsCrowned)
> > > 				{
> > > 					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Crowner", i);
> > > 					StrCat(sDetails, sizeof(sDetails), sTraslation);
> > > 				}
> > > 
> > > 				if (bMelee)
> > > 				{
> > > 					Format(sTraslation, sizeof(sTraslation), "%T", "WitchDetails_Melee", i);
> > > 					StrCat(sDetails, sizeof(sDetails), sTraslation);
> > > 				}
> > > 			}
> > > 			CPrintToChat(i, "%t", "WitchDamageFormat", sDamage, sShots, iClient, sDetails);
> > > 		}
> > > 
> > > 		CSkipList[i] = false;
> > > 	}
> > > }
> > > ```
> > 
> > 
> > that seems to be a good way to be. I had thought about this problem before and I did want to print the message in language per client. Good to see you have a lot work on this
> 
> Guess that panels can go like this, sending them in language per client.

I don't think it's possible.

**Comment by lechuga16** [comment]
I take back what I said, it seems it is possible

**Pull request closed without merging**
